/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qmgr;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    
	App classUnderTest = new App();
	
    @Test
    public void testNewTicket() {
        
        String sector = "PA";
        String received = "PA1";
        
        int esperado = received.length();
        int retornado = classUnderTest.getNewTicket(sector).length();
        
        assertEquals("Valida se um novo ticket é retornado", esperado, retornado);
        
    }
    
    @Test
    public void testNextCall() {
    	
    	String sector = "PA";
    	String nextTicket = "PA1";
    	assertEquals("Valida se o próximo ticket é chamado", nextTicket, classUnderTest.whoIsTheNext(sector));
    }
    
    
}
